import React, { useState, useEffect } from "react";
import { useOps } from "../../context/OpsContext";
import { Sparkles, X, CheckCircle2, ArrowRight, ShieldAlert, Clock, AlertTriangle } from "lucide-react";

export const AiDailyBriefModal = () => {
  const { isDailyBriefOpen, setIsDailyBriefOpen, openOrderDetail, setActiveTab } = useOps();
  const [brief, setBrief] = useState(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (isDailyBriefOpen) {
      setLoading(true);
      fetch("/api/ai/daily-brief")
        .then(r => r.json())
        .then(data => {
          setBrief(data);
          setLoading(false);
        })
        .catch(err => {
          console.error(err);
          setLoading(false);
        });
    }
  }, [isDailyBriefOpen]);

  if (!isDailyBriefOpen) return null;

  return (
    <div className="fixed inset-0 bg-slate-900/60 backdrop-blur-xs z-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl max-w-2xl w-full shadow-2xl border border-slate-200 overflow-hidden animate-in fade-in zoom-in-95">
        {/* Header */}
        <div className="bg-navy-900 text-white px-6 py-5 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-enterprise-600 flex items-center justify-center text-white shadow-md">
              <Sparkles size={20} />
            </div>
            <div>
              <h2 className="text-lg font-bold tracking-tight">Executive Daily Brief</h2>
              <p className="text-xs text-slate-300">Generated by OPSpulse Operational Intelligence Engine</p>
            </div>
          </div>
          <button
            onClick={() => setIsDailyBriefOpen(false)}
            className="text-slate-400 hover:text-white p-1 rounded-lg transition-colors"
          >
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-6 max-h-[75vh] overflow-y-auto">
          {loading ? (
            <div className="py-12 text-center space-y-3">
              <div className="w-8 h-8 border-3 border-enterprise-600 border-t-transparent rounded-full animate-spin mx-auto" />
              <p className="text-sm font-medium text-slate-600">Analyzing operational signals across departments...</p>
            </div>
          ) : brief ? (
            <>
              {/* Executive Summary Cards */}
              <div className="bg-slate-50 border border-slate-200 rounded-xl p-4 space-y-2">
                <h3 className="text-xs font-bold text-slate-400 uppercase tracking-wider">
                  Operational Status Summary
                </h3>
                <ul className="space-y-2 text-sm text-slate-700 font-medium">
                  {brief.summaryBullets.map((bullet, idx) => (
                    <li key={idx} className="flex items-start gap-2.5">
                      <span className="w-1.5 h-1.5 rounded-full bg-enterprise-600 mt-2 shrink-0" />
                      <span>{bullet}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Recommended Priorities */}
              <div className="space-y-3">
                <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider flex items-center gap-2">
                  <CheckCircle2 size={16} className="text-emerald-600" />
                  Recommended Action Priorities Today
                </h3>

                <div className="space-y-3">
                  {brief.recommendedPriorities.map((item) => (
                    <div
                      key={item.step}
                      className="bg-white border border-slate-200 hover:border-enterprise-300 rounded-xl p-4 transition-all shadow-2xs group flex items-start justify-between gap-4"
                    >
                      <div className="flex items-start gap-3">
                        <span className="w-6 h-6 rounded-full bg-enterprise-100 text-enterprise-700 font-bold text-xs flex items-center justify-center shrink-0 mt-0.5">
                          {item.step}
                        </span>
                        <div>
                          <h4 className="font-bold text-slate-900 text-sm group-hover:text-enterprise-600 transition-colors">
                            {item.title}
                          </h4>
                          <p className="text-xs text-slate-600 mt-0.5">{item.action}</p>
                        </div>
                      </div>

                      <button
                        onClick={() => {
                          setIsDailyBriefOpen(false);
                          if (item.targetId === "ORD-1042") {
                            openOrderDetail("ORD-1042");
                          } else if (item.targetId === "dept-finance") {
                            setActiveTab("analytics");
                          } else {
                            setActiveTab("risks");
                          }
                        }}
                        className="bg-slate-100 group-hover:bg-enterprise-600 group-hover:text-white text-slate-700 text-xs font-semibold px-3 py-1.5 rounded-lg flex items-center gap-1 transition-all shrink-0"
                      >
                        <span>Execute</span>
                        <ArrowRight size={14} />
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            </>
          ) : null}
        </div>

        {/* Footer */}
        <div className="bg-slate-50 px-6 py-4 border-t border-slate-200 flex items-center justify-between text-xs text-slate-500">
          <span>Real-time enterprise state synced</span>
          <button
            onClick={() => setIsDailyBriefOpen(false)}
            className="bg-slate-900 text-white font-semibold px-4 py-2 rounded-lg hover:bg-slate-800 transition-colors"
          >
            Close Executive Brief
          </button>
        </div>
      </div>
    </div>
  );
};
